use Java5_DivineShop
go

go
INSERT INTO [Account] (username, email, hash_password, is_enabled)
VALUES
('john', 'john@gmail.com', '$2y$10$sjnOuHMt7OQTXTODsPj6beOkyuNIVcI82kKosANwxXG.e9NuhgXlW', 1),
('mery', 'mery@gmail.com', '$2y$10$sjnOuHMt7OQTXTODsPj6beOkyuNIVcI82kKosANwxXG.e9NuhgXlW', 1),
('susan', 'susan@gmail.com','$2y$10$sjnOuHMt7OQTXTODsPj6beOkyuNIVcI82kKosANwxXG.e9NuhgXlW', 1);
-- ('john', 'john@gmail.com', '{bcrypt}$2y$10$sjnOuHMt7OQTXTODsPj6beOkyuNIVcI82kKosANwxXG.e9NuhgXlW', 1),
-- ('mery', 'mery@gmail.com', '{bcrypt}$2y$10$sjnOuHMt7OQTXTODsPj6beOkyuNIVcI82kKosANwxXG.e9NuhgXlW', 1),
-- ('susan', 'susan@gmail.com','{bcrypt}$2y$10$sjnOuHMt7OQTXTODsPj6beOkyuNIVcI82kKosANwxXG.e9NuhgXlW', 1);
go


-- Chèn dữ liệu vào bảng authorities
INSERT INTO [Roles] (username, role,username_user)
VALUES
('john', 'ROLE_EMPLOYEE','john'),
('mery', 'ROLE_EMPLOYEE','mery'),
('mery', 'ROLE_MANAGER','mery'),
('susan', 'ROLE_EMPLOYEE','susan'),
('susan', 'ROLE_MANAGER','susan'),
('susan', 'ROLE_ADMIN','susan');
go

insert into Product(ma_san_pham, ten_san_pham, tinh_trang, the_loai, gia_san_pham, percent_giam_gia, anh_san_pham, slug, danh_muc, mota, active_san_pham, soluong, soluongmua, soluotthich)
values
    ('Netflix-1', N'Netflix Premium 1 tháng - Tài khoản', 1, N'App, Giải trí, Xem phim' , 260000, 62, 'Netflix-1.png', 'tai-khoan-netflix-1-thang', N'Giải trí', N'Tài khoản sẽ được chia làm nhiều User, mỗi người sẽ được cấp 1 User riêng trong tài khoản để sử dụng Lưu ý chỉ sử dụng đúng user mang tên mình và không được đổi pass trong quá trình sử dụng. Khách hàng có thể đăng nhập trên nhiều thiết bị nhưng chỉ được sử dụng 1 thiết bị tại 1 thời điểm (Không xem phim trên nhiều thiết bị cùng lúc), Đăng nhập và xem phim tại: Đăng nhập Netflix (Lưu ý: Tài khoản không hỗ trợ sử dụng trên máy chiếu', 1, 100, 1000, 1000),
    (	'Spotify-2', N'Spotify Premium 1 năm - Gia hạn chính chủ', 1, 	N'App, Giải trí, Spotify, Nghe nhạc', 	590000, 	49, 	'Spotify-2.png', 	'goi-gia-han-spotify-premium-12m', 	N'Giải trí', N'Spotify là ứng dụng nghe nhạc bản quyền nổi tiếng trên toàn thế giới. Spotify có hàng triệu bản nhạc từ tất cả mọi nơi trên thế giới bao gồm cả các bài hát ở Việt Nam. ', 1, 197, 2, 308),
    (	'YouTube-3',	N'YouTube Premium + YouTube Music 6 tháng - Gia hạn chính chủ', 1, 	N'App, Giải trí, Youtube', 	3360000,	92,	'YouTube-3.png', 	'youtube-premium-6-month', 	N'Giải trí',	N'YouTube Premium, bạn có thể xem hàng triệu video không có quảng cáo. Quảng cáo bao gồm cả quảng cáo trước và trong video cũng như quảng cáo biểu ngữ, quảng cáo đi kèm kết quả tìm kiếm và quảng cáo lớp phủ trên video. Bạn vẫn có thể xem quảng cáo hoặc thương hiệu nhúng trong nội dung của người sáng tạo mà YouTube không kiểm soát.', 1, 100, 900, 900),
    (	'YouTube-4', 	N'YouTube Premium + YouTube Music 1 năm - Gia hạn chính chủ', 1, 	N'App, Giải trí, Youtube', 	6720000, 	93, 	'YouTube-4.png',	'gia-han-youtube-premium-12-thang', 	N'Giải trí',	N'YouTube Premium, bạn có thể xem hàng triệu video không có quảng cáo. Quảng cáo bao gồm cả quảng cáo trước và trong video cũng như quảng cáo biểu ngữ, quảng cáo đi kèm kết quả tìm kiếm và quảng cáo lớp phủ trên video. Bạn vẫn có thể xem quảng cáo hoặc thương hiệu nhúng trong nội dung của người sáng tạo mà YouTube không kiểm soát.', 1, 100, 800, 800),
    (	'Tidal-5', 	N'Tidal HiFi Plus 1 tháng - Tài khoản nghe nhạc', 1, 	N'App, Giải trí, Youtube', 	550000, 	97, 	'Tidal-5.png', 	'tai-khoan-nghe-nhac-tidal-hifi-plus-1m', 	N'Giải trí', N'Tidal là một trong những dịch vụ Stream Music hỗ trợ chất lượng Lossless, High Res, MQA cho phép bạn thưởng thức hàng chục triệu bài hát chất lượng cao trên toàn thế giới.', 1, 74, 295, 47),
    (	'Netflix-6', 	N'Netflix Premium 1 ngày - Tài khoản', 1	, 	N'App, Giải trí, Xem phim', 	99000, 	75,   'Netflix-6.png', 	'tai-khoan-netflix-1-user-1-ngay', N'Giải trí', N'Tài khoản sẽ được chia làm nhiều User, mỗi người sẽ được cấp 1 User riêng trong tài khoản để sử dụng. Lưu ý chỉ sử dụng đúng user mang tên mình và không được đổi pass trong quá trình sử dụng. Tài khoản có thể đăng nhập được cho nhiều thiết bị tuy nhiên sẽ chỉ dùng 1 thiết bị trong 1 thời điểm. (Lưu ý: Không sử dụng được trên máy chiếu)', 1, 100, 800, 800),
    (	'Youtube-7',	N'Kích hoạt Youtube Premium trên TV (1 năm)', 1	, 	N'App, Giải trí, Youtube', 	479000, 	60, 	'Youtube-7.png', 	'kich-hoat-youtube-premium-tv-1-nam', 	N'Giải trí', N'YouTube Premium, bạn có thể xem hàng triệu video không có quảng cáo. Quảng cáo bao gồm cả quảng cáo trước và trong video cũng như quảng cáo biểu ngữ, quảng cáo đi kèm kết quả tìm kiếm và quảng cáo lớp phủ trên video. Bạn vẫn có thể xem quảng cáo hoặc thương hiệu nhúng trong nội dung của người sáng tạo mà YouTube không kiểm soát.',1, 168, 275, 446),
    (	'Youtube-8', 	N'Kích hoạt Youtube Premium trên TV (6 tháng)', 1, 	N'App, Giải trí, Youtube', 	239000,	59, 	'Youtube-8.png', 	'kich-hoat-youtube-premium-tv-6-thang', 	N'Giải trí', N'YouTube Premium, bạn có thể xem hàng triệu video không có quảng cáo. Quảng cáo bao gồm cả quảng cáo trước và trong video cũng như quảng cáo biểu ngữ, quảng cáo đi kèm kết quả tìm kiếm và quảng cáo lớp phủ trên video. Bạn vẫn có thể xem quảng cáo hoặc thương hiệu nhúng trong nội dung của người sáng tạo mà YouTube không kiểm soát.',1, 100, 700, 1000),
    (	'Netflix-9',	N'Netflix Premium 1 Tháng - Tài khoản Quốc tế + Tài khoản HMA VPN', 1,	N'App, Giải trí, Xem phim', 	260000, 	70, 	'Netflix-9.png', 	'tai-khoan-netflix-1-thang-quoc-te', 	N'Giải trí', '' ,1, 463, 546, 397),
    (	'NoPing-10', 	N'NoPing 1 tháng - Code kích hoạt', 1, 	N'Giải trí, App, New', 	220000, 	46, 	'NoPing-10.png', 	'code-noping-1m', 	N'Giải trí', N'NoPing là một phần mềm giúp giảm độ trễ (ping) và cải thiện kết nối Internet khi chơi game online. Đây là một công cụ vô cùng hữu ích dành cho game thủ, giúp họ có thể tận hưởng trải nghiệm chơi game mượt mà và phản ứng nhanh nhạy hơn.',1, 513, 168, 505),
    (	'Netflix-11', 	N'Netflix Premium Extra 1 tháng - Tài khoản', 1, N'App, Giải trí, Xem phim',	260000, 	58,	'Netflix-11.png', 	'tai-khoan-netflix-1-thang-extra', 	N'Giải trí', N'Tài khoản sẽ được chia làm nhiều User, mỗi người sẽ được cấp 1 User riêng trong tài khoản để sử dụng. Lưu ý chỉ sử dụng đúng user mang tên mình và không được đổi pass trong quá trình sử dụng. Tài khoản có thể đăng nhập được cho nhiều thiết bị tuy nhiên sẽ chỉ dùng 1 thiết bị trong 1 thời điểm. (Lưu ý: Không sử dụng được trên máy chiếu',1, 82, 439, 372),
    (	'Netflix-12',	N'Netflix Premium Extra 6 tháng - Tài khoản', 1,	N'App, Giải trí, Xem phim', 	1560000,	58, 	'Netflix-12.png',	'tai-khoan-netflix-6-thang', N'Giải trí', N'Tài khoản sẽ được chia làm nhiều User, mỗi người sẽ được cấp 1 User riêng trong tài khoản để sử dụng. Lưu ý chỉ sử dụng đúng user mang tên mình và không được đổi pass trong quá trình sử dụng. Tài khoản có thể đăng nhập được cho nhiều thiết bị tuy nhiên sẽ chỉ dùng 1 thiết bị trong 1 thời điểm. (Lưu ý: Không sử dụng được trên máy chiếu', 1, 333, 340, 614),
    (	'Netflix-13',	N'Netflix Premium Extra 3 tháng - Tài khoản', 1,	N'App, Giải trí, Xem phim',	780000,	58,	'Netflix-13.png',	'tai-khoan-netflix-3-thang',	N'Giải trí', N'Tài khoản sẽ được chia làm nhiều User, mỗi người sẽ được cấp 1 User riêng trong tài khoản để sử dụng. Lưu ý chỉ sử dụng đúng user mang tên mình và không được đổi pass trong quá trình sử dụng. Tài khoản có thể đăng nhập được cho nhiều thiết bị tuy nhiên sẽ chỉ dùng 1 thiết bị trong 1 thời điểm. (Lưu ý: Không sử dụng được trên máy chiếu', 1, 430, 233, 234),
    (	'Spotify-14',	N'Gói gia hạn Spotify Premium 6 tháng',	0, 	N'App, Giải trí, Spotify, Nghe nhạc', 	590000,	73,	'Spotify-14.png', 	'gia-han-spotify-premium-6m',	N'Giải trí', N'Spotify là ứng dụng nghe nhạc bản quyền nổi tiếng trên toàn thế giới. Spotify có hàng triệu bản nhạc từ tất cả mọi nơi trên thế giới bao gồm cả các bài hát ở Việt Nam.',1, 171, 404, 667),
    (	'Spotify-15',	N'Tài khoản nghe nhạc Spotify Premium (1 tháng)', 0,	N'App, Giải trí, Spotify, Nghe nhạc', 	59000,	68,	'Spotify-15.png',	'tai-khoan-spotify-1-thang',	N'Giải trí', N'Spotify là ứng dụng nghe nhạc bản quyền nổi tiếng trên toàn thế giới. Spotify có hàng triệu bản nhạc từ tất cả mọi nơi trên thế giới bao gồm cả các bài hát ở Việt Nam.', 1, 18, 299, 620),
    ( 'YouTube-16', 	N'Gia hạn YouTube Premium + YouTube Music (1 Tháng)', 0,	N'App, Giải trí, Youtube', 	280000,	91,	'YouTube-16.png',	'youtube-premium-1-month', 	N'Giải trí',	N'YouTube Premium, bạn có thể xem hàng triệu video không có quảng cáo. Quảng cáo bao gồm cả quảng cáo trước và trong video cũng như quảng cáo biểu ngữ, quảng cáo đi kèm kết quả tìm kiếm và quảng cáo lớp phủ trên video. Bạn vẫn có thể xem quảng cáo hoặc thương hiệu nhúng trong nội dung của người sáng tạo mà YouTube không kiểm soát.', 1, 497, 589, 479),
    (	'YouTube-17', 	N'Gia hạn YouTube Premium + YouTube Music (2 Tháng)', 0, 	N'App, Giải trí, Youtube', 	560000,	91, 	'YouTube-17.png', 	'youtube-premium-2-month', 	N'Giải trí', N'YouTube Premium, bạn có thể xem hàng triệu video không có quảng cáo. Quảng cáo bao gồm cả quảng cáo trước và trong video cũng như quảng cáo biểu ngữ, quảng cáo đi kèm kết quả tìm kiếm và quảng cáo lớp phủ trên video. Bạn vẫn có thể xem quảng cáo hoặc thương hiệu nhúng trong nội dung của người sáng tạo mà YouTube không kiểm soát.', 1, 642, 679, 242),
    (	'YouTube-18', 	N'Tài khoản Youtube Premium tạo sẵn (4 tháng)', 0, 	N'App, Giải trí, Youtube', 	1100000,	91,	'YouTube-18.png', 	'tai-khoan-youtube-premium', 	N'Giải trí', N'YouTube Premium, bạn có thể xem hàng triệu video không có quảng cáo. Quảng cáo bao gồm cả quảng cáo trước và trong video cũng như quảng cáo biểu ngữ, quảng cáo đi kèm kết quả tìm kiếm và quảng cáo lớp phủ trên video. Bạn vẫn có thể xem quảng cáo hoặc thương hiệu nhúng trong nội dung của người sáng tạo mà YouTube không kiểm soát.',1, 246, 567, 98),
    (	'Spotify-19', 	N'Tài khoản nghe nhạc Spotify Premium (4 tháng)', 0,	N'App, Giải trí, Spotify, Nghe nhạc', 	236000,	67, 	'Spotify-19.png',	'spotify-premium-4m', 	N'Giải trí', N'YouTube Premium, bạn có thể xem hàng triệu video không có quảng cáo. Quảng cáo bao gồm cả quảng cáo trước và trong video cũng như quảng cáo biểu ngữ, quảng cáo đi kèm kết quả tìm kiếm và quảng cáo lớp phủ trên video. Bạn vẫn có thể xem quảng cáo hoặc thương hiệu nhúng trong nội dung của người sáng tạo mà YouTube không kiểm soát.', 1, 55, 613, 433),
    (	'Deezer-20', 	N'Deezer HiFi 1 Tháng - Tài khoản nghe nhạc', 0,	N'App, Spotify, Giải trí', 	288000,	93, 	'Deezer-20.png', 'tai-khoan-nghe-nhac-deezer-1m',N'Giải trí' ,N'Deezer là một trong những dịch vụ Stream Music hỗ trợ chất lượng Lossless, cho phép bạn thưởng thức hàng chục triệu bài hát chất lượng cao trên toàn thế giới.',1, 477, 73, 195),
    (	'Malwarebytes-21',	N'Malwarebytes - Key bản quyền diệt virus vĩnh viễn', 1,	N'App, Làm việc',	599000,	60,	'Malwarebytes-21.png', 	'malwarebytes-key-ban-quyen-diet-virus-vinh-vien',	N'Diệt Virus', N'Malwarebytes Premium là gì. Malwarebytes Premium hiện hoạt động như một phần mềm chống vi-rút toàn diện chứ không chỉ là một trợ lý cho phần mềm chống vi-rút. Malwarebytes Premium giành được điểm số xuất sắc 10/10 trong các bài kiểm tra từ các phòng thí nghiệm độc lập trong việc phát hiện và tiêu diệt các phần mềm độc hại như Backdoor, PornTool, PUP, Ransom, RiskWare, Spyware, Trojan...',1, 546, 212, 72),
    (	'Kaspersky-22',	N'Kaspersky Standard 1 năm (1 thiết bị) - Nâng cấp chính chủ',	1,	N'kaspersky, anti-virus, Diệt virus, Làm việc',	159000,	12,	'Kaspersky-22.png',	'kaspersky-standard-1-nam-1-thiet-bi-nang-cap-chinh-chu',	N'Diệt Virus', N'Bộ sản phẩm bảo mật nâng cao – máy tính cá nhân. Bảo vệ chống virus, mã độc mã hóa tống tiền, lừa đảo, thư rác và nhiều tính năng khác Bảo vệ máy tính cá nhân Bảo vệ quyền riêng tư, thông tin liên lạc, danh tính và thông tin của bạn Giúp bảo vệ kết nối trực tuyến của bạn - ngay cả trên Wi-Fi công cộng Bảo vệ tiền bạc & thông tin chi tiết về tài khoản của bạn khi bạn mua sắm và giao dịch ngân hàng trực tuyến Hoạt động “ngầm” - vì vậy thiết bị của bạn có thể duy trì hiệu suất tốt Đơn giản hóa bảo mật - với khả năng bảo vệ dễ thiết lập & khởi chạy', 1, 382, 502, 595),
    (	'Bitdefender-23',	N'Bitdefender Total Security 3 tháng (5 thiết bị) - Code gia hạn', 1,	N'App, Diệt virus', 	149000,	64, 	'Bitdefender-23.png',	'bitdefender-total-security-3-thang-5-thiet-bi-code-gia-han',	N'Diệt Virus', N'Một sản phẩm có khả năng bảo vệ tất cả các thiết bị của bạn mà không làm chậm hiệu suất Bitdefender vượt qua tất cả các phần mềm bảo mật khác về cả Bảo vệ tốt nhất lẫn Tác động thấp nhất đến Hiệu suất. Bảo vệ thiết bị của bạn khỏi phần mềm độc hại mà không làm giảm tốc độ. Phát hiện mối đe dọa vượt trội để ngăn chặn phần mềm độc hại tinh vi Các công nghệ tiên tiến giúp bảo vệ khỏi các cuộc tấn công zero-day Bảo vệ nhiều lớp ransomware để giữ an toàn cho dữ liệu của bạn Kiểm soát của phụ huynh Kiểm soát nâng cao của phụ huynh để giữ cho con bạn an toàn khi trực tuyến Tác động rất ít đến hiệu suất hệ thống của bạn Hỗ trợ các hệ điều hành : MacOS, Android, Windows và iOs ',1, 393, 76, 27),
    (	'360-24',	N'360 Total Security Premium (1 năm / 3 PC)', 1,	N'App, Làm việc, Diệt virus', 	249000,	53,	'360-24.png', 	'360-total-security-premium-1-nam-3-pc', 	N'Diệt Virus', N'Trình chống theo dõi sự riêng tư Ngăn chặn các trang web theo dõi hành vi trực tuyến của bạn, giúp bạn tránh nguy cơ bị quảng cáo nhắm mục tiêu và rò rỉ sự riêng tư Desktop Organizer Trợ lý màn hình nâng cao để dọn sạch màn hình lộn xộn bằng một lần nhấp chuột và giữ cho màn hình luôn gọn gàng. Cung cấp tìm kiếm tập tin, lối tắt ảnh chụp màn hình, quản lý danh sách việc cần làm, tin tức hàng ngày và nhiều tiện ích hữu ích khác. Trình Hủy Dữ Liệu Sau khi xóa, mọi thứ bạn muốn giữ bí mật vẫn có thể được khôi phục bởi bất cứ ai có quyền truy cập vào ổ cứng của bạn. Trình Hủy Dữ Liệu phá hủy hoàn toàn các tập tin đã xóa. Một khi đã bị xóa đi, chúng sẽ đi mãi. Bảo vệ sự riêng tư Bất cứ khi nào bạn làm việc với máy tính, bạn đều để lại dấu vết kỹ thuật số. Trình dọn dẹp bảo vệ riêng tư xóa bỏ hoàn toàn mọi dấu vết của bạn, bao gồm cả lịch sử trình duyệt, hoạt động chương trình, lịch sử vận hành hệ thống. Trình phân tích đĩa Hãy xem qua những gì đang chiếm dung lượng đĩa của bạn. Các tệp được sắp xếp theo thứ tự kích cỡ, cho bạn gợi ý xem mình cần bắt đầu dọn dẹp như thế nào và dễ dàng xóa các tệp không sử dụng một cách dễ dàng để giải phóng dung lượng lưu trữ của bạn Trình cập nhật driver Trình cập nhật driver giúp dễ dàng luôn cập nhật cho tất cả trình điều khiển của bạn.Tính năng sao lưu được tích hợp sẵn cung cấp một biện pháp phòng ngừa khác cho phép bạn khôi phục lại phiên bản trước đó khi trình điều khiển không thể hoạt động đúng chức năng. Tường lửa Tường lửa theo dõi mức sử dụng băng thông của ứng dụng, điều tiết tổng lưu lượng và ngăn chặn các truy cập đáng ngờ vào Internet để đảm bảo giao tiếp mạng an toàn hơn và nhanh hơn. Dọn dẹp theo lịch Cài đặt dọn dẹp thường xuyên tự động để đảm bảo máy tính của bạn không có bộ nhớ đệm rác, tệp rác và sự cố hiệu suất.', 1, 166, 60, 676),
    (	'ESET-25', 	N'ESET Endpoint Security 1 năm - Nâng cấp chính chủ', 1, 	N'App, Diệt virus',	490000, 	90, 	'ESET-25.jpg', 	'eset-endpoint-security-1-nam-nang-cap-chinh-chu', 	N'Diệt Virus', N'ESET là một phần mềm chống vi-rút an toàn thực sự trong việc bảo vệ thiết bị của bạn khỏi các phần mềm độc hại, các mưu đồ lừa đảo, ransomware và nhiều mối đe dọa trực tuyến khác. ESET giữ cho thiết bị của bạn an toàn khi trực tuyến. Ngoài ra, ESET còn có một số tính năng tuyệt vời để giúp bạn khôi phục thiết bị của mình nếu nó bị mất hoặc bị đánh cắp. Nó cũng cho phép bạn theo dõi ai đang đăng nhập vào bộ định tuyến Wi-Fi của bạn.',1, 608, 165, 541),
    (	'Avast-26',	N'Code kích hoạt Avast Ultimate (1 năm - 1 thiết bị)',	1,	N'App, Diệt Virus, New',	249000,	88,	'Avast-26.png', 	'code-kich-hoat-avast-ultimate-1-nam-1-thiet-bi', 	N'Diệt Virus', N'Avast Ultimate là gói cước cao nhất của Avast bao gồm tất cả các tính năng của Avast Premium Security, Avast SecureLine VPN, AntiTrack Premium, Cleanup Premium...- Ngăn chặn virus, phần mềm gián điệp, phần mềm tống tiền và phần mềm độc hại. - Mua sắm và giao dịch ngân hàng trực tuyến an toàn mọi lúc, mọi nơi. - Tránh trang web nguy hiểm và giả mạo. - Dùng tường lửa nâng cao để ngăn chặn kẻ xâm nhập. - Bảo vệ dữ liệu cá nhân và tài liệu nhạy cảm. - Tránh xa hành vi lừa đảo trong hộp thư - Ẩn hoạt động trên mạng khỏi tin tặc, nhà cung cấp dịch vụ Internet, v.v. - Ẩn địa chỉ IP và đảm bảo sự riêng tư. - Đảm bảo sự riêng tư cho vị trí thực và hoạt động trên mạng. - Mua sắm và thực hiện giao dịch ngân hàng an toàn nhờ kết nối được mã hóa. - Kết nối an toàn với điểm phát sóng bất kỳ, ngay cả trên Wi-Fi công cộng. - Tránh được hoạt động chặn theo vị trí địa lý và truy cập vào nội dung yêu thích. - Ẩn dấu vân tay trực tuyến để tránh quảng cáo nhắm mục tiêu. - Ngăn kẻ theo dõi thu thập và chia sẻ dữ liệu. - Nhận thông báo về các lượt theo dõi. - Phát hiện những ai đang tìm cách theo dõi bạn. - Ngụy trang cho hoạt động trực tuyến của bạn khi duyệt web. - Ngăn kẻ theo dõi thu thập và chia sẻ dữ liệu. - Ngay lập tức chặn các hành vi theo dõi. - Dọn sạch tập tin rác để có thêm không gian lưu trữ. - Thiết lập chế độ tự động bảo trì thường xuyên để dọn sạch tập tin rác. - Dùng công cụ dọn dẹp ổ đĩa để xóa các tập tin còn lại một cách an toàn.',1, 72, 46, 4),
    (	'Kaspersky-27', 	N'Kaspersky Premium 1 năm (1 thiết bị) - Nâng cấp chính chủ',	1,	N'Làm việc, kaspersky, anti-virus, Diệt virus',	199000,	70,	'Kaspersky-27.png', 	'kaspersky-premium-1-nam-1-thiet-bi-nang-cap-chinh-chu', 	N'Diệt Virus', N'Các tính năng về quyền riêng tư - Duyệt mạng riêng tư và không bị gián đoạn - Bảo vệ thông tin cá nhân & thanh toán. Các tính năng về hiệu năng - Trình theo dõi tình trạng và dọn dẹp ổ cứng - Tối ưu hóa hiệu năng - Giải trí không bị gián đoạn',1, 430, 233, 234),
    (	'PandaDomeComplete-28', 	N'Code kích hoạt Panda Dome Complete (1 năm - 1 thiết bị)', 1,	N'App, PandaDome, New, Diệt Virus',	490000,	70,	'PandaDomeComplete-28.png', 	'code-kich-hoat-panda-dome-complete-1-nam-1-thiet-bi',	N'Diệt Virus', N'Panda Dome Complete - một phần mềm diệt virus mạnh mẽ giúp bạn bảo vệ quyền riêng tư và tối ưu hóa tất cả các thiết bị của mình. Điểm nổi bật: Bảo vệ chống virus thời gian thực Bảo vệ thiết bị của bạn khỏi mọi mối đe dọa. Duyệt, mua sắm và giao dịch ngân hàng trực tuyến mà không phải lo lắng Với mô-đun duyệt web an toàn Panda Dome Essential, bạn có thể tránh các trang web lừa đảo và các cuộc tấn công lừa đảo. Tinh chỉnh PC Làm sạch và tối ưu hóa PC của bạn để có hiệu suất tốt hơn. Trình quản lý mật khẩu Quản lý và bảo vệ mật khẩu của bạn chỉ bằng một cú nhấp chuột.',1, 18, 299, 620),
    (	'Avast-29',	N'Code kích hoạt Avast Mobile Ultimate (1 năm - 1 thiết bị Android)',	1,	N'App, Diệt Virus, New',	149000,	93,	'Avast-29.png',	'code-kich-hoat-avast-mobile-ultimate-1-nam-1-thiet-bi-android',	N'Diệt Virus', N'Avast Ultimate là gói cước cao nhất của Avast bao gồm tất cả các tính năng của Avast Premium Security, Avast SecureLine VPN, AntiTrack Premium, Cleanup Premium... - Ngăn chặn virus, phần mềm gián điệp, phần mềm tống tiền và phần mềm độc hại. - Mua sắm và giao dịch ngân hàng trực tuyến an toàn mọi lúc, mọi nơi. - Tránh trang web nguy hiểm và giả mạo. - Dùng tường lửa nâng cao để ngăn chặn kẻ xâm nhập. - Bảo vệ dữ liệu cá nhân và tài liệu nhạy cảm. - Tránh xa hành vi lừa đảo trong hộp thư - Ẩn hoạt động trên mạng khỏi tin tặc, nhà cung cấp dịch vụ Internet, v.v. - Ẩn địa chỉ IP và đảm bảo sự riêng tư. - Đảm bảo sự riêng tư cho vị trí thực và hoạt động trên mạng. - Mua sắm và thực hiện giao dịch ngân hàng an toàn nhờ kết nối được mã hóa. - Kết nối an toàn với điểm phát sóng bất kỳ, ngay cả trên Wi-Fi công cộng. - Tránh được hoạt động chặn theo vị trí địa lý và truy cập vào nội dung yêu thích. - Ẩn dấu vân tay trực tuyến để tránh quảng cáo nhắm mục tiêu. - Ngăn kẻ theo dõi thu thập và chia sẻ dữ liệu. - Nhận thông báo về các lượt theo dõi. - Phát hiện những ai đang tìm cách theo dõi bạn. - Ngụy trang cho hoạt động trực tuyến của bạn khi duyệt web. - Ngăn kẻ theo dõi thu thập và chia sẻ dữ liệu. - Ngay lập tức chặn các hành vi theo dõi. - Dọn sạch tập tin rác để có thêm không gian lưu trữ. - Thiết lập chế độ tự động bảo trì thường xuyên để dọn sạch tập tin rác. - Dùng công cụ dọn dẹp ổ đĩa để xóa các tập tin còn lại một cách an toàn.',1, 55, 613, 433),
    (	'PandaDomeComplete-30',	N'Code kích hoạt Panda Dome Complete (1 năm - 3 thiết bị)',	1,	N'App, PandaDome, New, Diệt Virus',	790000,	52,	'PandaDomeComplete-30.png',	'panda-dome-complete-1y-3pc',	N'Diệt Virus', N'Panda Dome Complete - một phần mềm diệt virus mạnh mẽ giúp bạn bảo vệ quyền riêng tư và tối ưu hóa tất cả các thiết bị của mình.Điểm nổi bật: Bảo vệ chống virus thời gian thực Bảo vệ thiết bị của bạn khỏi mọi mối đe dọa. Duyệt, mua sắm và giao dịch ngân hàng trực tuyến mà không phải lo lắng Với mô-đun duyệt web an toàn Panda Dome Essential, bạn có thể tránh các trang web lừa đảo và các cuộc tấn công lừa đảo. Tinh chỉnh PC Làm sạch và tối ưu hóa PC của bạn để có hiệu suất tốt hơn. Trình quản lý mật khẩu Quản lý và bảo vệ mật khẩu của bạn chỉ bằng một cú nhấp chuột.',1, 55, 613, 433),
    (	'random-code-steam-31',	N'Random Code Steam',	1,	N'steam, random',	9000,	55,	'random-code-steam-31.png',	'random-code-steam',	'Steam', N'Random Code Steam giúp bạn nhận một game ngẫu nhiên vào tài khoản Steam. Có thể là một game 1$ cũng có thể lên tới vài chục $, tất cả phụ thuộc vào may mắn của bạn.',1, 168, 275, 446),
    (	'Elden Ring-32',	N'Elden Ring (CD Key Steam)',	0,	N'Action, RPG',	790000,	1,	'Elden Ring-32.jpg', 	'elden-ring-cd-key',	'Steam', N'Elden Ring là bom tấn nhập vai hành động sắp ra mắt được phát triển bởi FromSoftware và do Bandai Namco Entertainment phát hành. Trò chơi là sự hợp tác giữa đạo diễn Hidetaka Miyazaki của Dark Souls và tiểu thuyết gia George RR Martin - “cha đẻ” của Trò chơi vương quyền.',1, 100, 1000, 1000),
    (	'Grand-Theft-Auto-V-33',	N'Tài khoản Grand Theft Auto V: Premium Edition (GTA 5)',	0,	N'acc, gta, gta5, roleplay, tài khoản, accgame, gta v, gtav, accgame',	250000,	46,	'Grand-Theft-Auto-V-33.jpg',	'tai-khoan-gta5',	'Steam', N'"Grand Theft Auto V (còn được gọi là Grand Theft Auto 5, GTA 5  hoặc GTA V) là trò chơi video được phát triển bởi Rockstar North thuộc hãng Rockstar Games. Là phiên bản thứ năm trong Dòng trò chơi Grand Theft Auto  và là phần kế tiếp của Grand Theft Auto IV . Bản gốc của trò chơi chính thức được phát hành vào ngày 17 Tháng 9 năm 2013 cho phiên bản Xbox 360 và PlayStation 3. Trò chơi cũng đã được phát hành cho phiên bản Xbox One và PlayStation 4  vào ngày 18 tháng 11 năm 2014, sau đó phát hành cho PC vào ngày 14 tháng 4 năm 2015.',1, 18, 299, 620),
    (	'Assassins-Creed-Origins-34',	N'Assassins Creed Origins - Gold Edition',	0,	N'Action, Adventure, RPG',	1485000,	0, 	'Assassins-Creed-Origins-34.jpg', 	N'assassins-creed®-origins-gold-edition',	'Steam', N'Assassins Creed® Origins - Gold Edition là phiên bản cao cấp của game, bản này bao gồm:- Game gốc Assassins Creed® Origins - Nhiệm vụ độc quyền Ambush at Sea - Desert Cobra pack bao gồm: 1 outfit, 2 legendary weapons, 1 legendary shield và 1 vật cưỡi. - 3 Ability points - Assassins Creed Origins - Season Pass',1, 608, 165, 541),
    (	'Fly-Simulator-35',	N'Fly Simulator',	0,	N'Action, Indie, Simulation',	45000,	0,	'Fly-Simulator-35.jpg',	'fly-simulator',	'Steam', N'Bạn sẽ vào vai một bồi bàn và dẫn đầu một cuộc chiến khó khăn cho khách hàng của mình. Bạn đẩy lùi ruồi khỏi thức ăn, nếu không bạn sẽ không bao giờ nhận được bất cứ thứ gì. Có thể bạn là một con côn trùng đói đang cố gắng tăng dân số của bạn? Chọn phe đối lập. Cuộc chiến đã được tiến hành.', 1, 55, 613, 433),
    (	'Lords-of-the-Fallen-Game-of-the-Year-Edition-36',	N'Lords of the Fallen Game of the Year Edition',	0,	N'Action, RPG',	399000,	0,	'Lords-of-the-Fallen-Game-of-the-Year-Edition-36.jpg',	'lords-of-the-fallen-game-of-the-year-edition',	'Steam', N'Lords of the Fallen Game of the Year Edition',1, 126, 697, 304),
    (	'Mortal-Kombat-11-Ultimate-Edition-Global-37',	N'Mortal Kombat 11 Ultimate Edition Global - CD Key',	1,	N'Action',	599000,	39,	'Mortal-Kombat-11-Ultimate-Edition-Global-37.jpg',	'mk11-ultimate-cdkey',	'Steam',N' Like the previous three games in the series, including Mortal Kombat Mobile, Mortal Kombat 11 is a 2.5D fighting game. Alongside the returning Fatalities, Brutalities, Stage Fatalities, Friendships and Quitalities, new gameplay features are introduced, such as Fatal Blows and Krushing Blows.		',1, 246, 567, 98),
    (	'Left-4-Dead-2-38',	N'Left 4 Dead 2',	0,	N'Action',	142000,	0,	'Left-4-Dead-2-38.jpg',	'left-4-dead-2',	'Steam', N'"Cốt truyện tương tự như Left 4 Dead ; nó liên quan đến hậu quả của Nhiễm trùng một tuần sau các sự kiện của trò chơi trước đó, bây giờ là khoảng ba tuần sau khi Nhiễm trùng đầu tiên.',1, 460, 554, 141),
    (	'DARK-SOULS-39',	N'DARK SOULS: REMASTERED',	0,	N'Action',	850000,	0,	'DARK-SOULS-39.jpg',	'dark-souls-remastered',	'Steam', N'Lửa từ đó mà sinh ra. Trải nghiệm lại trò chơi xác định thể loại Soullike, được giới phê bình đánh giá cao đã bắt đầu tất cả. Được chỉnh sửa lại đẹp mắt, trở lại Lordran với chi tiết độ nét cao tuyệt đẹp chạy ở tốc độ 60 FPS. Dark Souls Remastered bao gồm trò chơi chính cộng với DLC Artorias of the Abyss.', 1, 197, 2, 308),
    (	'DARK-SOULS-40',	N'DARK SOULS III',	0,	N'Action',	970000,	0,	'DARK-SOULS-40.jpg',	'dark-souls-iii',	'Steam', N'Dark Souls 3 là tựa game nhập vai hành động được phát hành cho Xbox One, PS 4 và PC; trong đó, người chơi sẽ bước vào một thế giới gothic kỳ bí để chiến đấu chống lại những thế lực hắc ám, bạo tàn. Bảy năm kể từ sự ra đời của Souls Demon, Dark Souls 3 đã là phiên bản thứ 4 trong seri nổi tiếng Souls game của hãng From Software. Để tạo ra sự kết nối với Dark Souls 1 va 2, những sự kiện liên kết và nhiều đoạn chuyển cảnh sẽ giúp bạn hiểu rõ hơn về bối cảnh và nội dung của trò chơi. Tuy nhiên, với những người chơi chưa trải nghiệm qua Dark Souls 1, 2, các bạn cũng không phải lo lắng khi nội dung của phần 3 khá độc lập. Trong Dark Souls 3, người chơi sẽ đến với lãnh địa Lothric, vùng đất của tro tàn và hoang phế. Nhiệm vụ chính của bạn là phải tiêu diệt tên trùm bóng tối có tên “Lords of Cinder” để trả lại sự bình yêu cho vùng đất này.',1, 72, 46, 4),
    (	'Zoom-Pro-41',	N'Zoom Pro 1 tháng - Gói nâng cấp',	 1,	N'App, Làm việc, Học tập',	210000,	40,	'Zoom-Pro-41.jpg',	'nang-cap-tai-khoang-zoom-1-thang',	N'Làm việc',	N'Zoom hay Zoom Cloud Meetings là phần mềm họp hội nghị trực tuyến đa điểm hoạt động trên môi trường internet. - Các ứng dụng như Skype, facebook, zalo cũng có thể gọi nhóm được nhưng tính năng sẽ rất bị hạn chế. - Zoom ra đời là giải pháp để thay đổi việc khách hàng đầu tư một hệ thống hội nghị truyền hình dạng thiết bị cứng tốn rất nhiều chi phí đầu tư và vận hành, không linh hoạt. - Zoom có những tính năng vượt trội so với các phần mềm khác. - Trong môi trường sư phạm, Zoom Meetings thường được ứng dụng để giảng dạy, hội họp, hội thảo trực tuyến với khả năng cho phép kết nối hàng trăm người một lúc.', 1, 205, 360, 52),
    (	'Windows-10-Professional-42',	N'Windows 10 Professional - CD Key',	1,	N'windows, Làm việc, microsoft',	400000,	28,	'Windows-10-Professional-42.png',	'windows-10-professional-retail-pc-cd-key',	N'Làm việc',	N'Hướng dẫn kích hoạt key Retail bản quyền cho Windows 10  **Lưu ý: - Trước khi add code thì máy bạn phải cài Win 10 Pro và chưa Crack. - Chỉ sử dụng trên một máy và một tài khoản Microsoft. Các lần cài win sau tự động active theo main của máy và tài khoản này.',1, 377, 414, 125),
    (	'Canva-Pro-43',	N'Canva Pro 1 năm - Gia hạn chính chủ',  1,	N'App, Làm việc, Thiết kế',	1500000,	80,	'Canva-Pro-43.png',	'canvas-1-year',	N'Làm việc',	N'Tài khoản Canva giá rẻ chứa đầy đủ tài nguyên thiết kế miễn phí mà bạn có thể sử dụng ngay từ bên trong ứng dụng hoặc trang web và bắt đầu tạo đồ họa cho trang web, banner, mẫu bìa quảng cáo và phương tiện truyền thông xã hội của bạn. Canva là một công cụ tuyệt vời cho mọi người phải tạo đồ họa hoặc chỉnh sửa ảnh trong thời gian ngắn mà không cần bất kỳ kỹ năng thiết kế nào.',1	,238, 644, 561),
    (	'chatgpt-44',	N'ChatGPT (OpenAI) - Tài khoản',	1,	N'openai, chatgpt, tài khoản, study, work, học tập, làm việc, ai, ai chat bot',	200000,	85,	'chatgpt-44.jpg',	'tai-khoan-chatgpt-openai',	N'Làm việc',	N'"ChatGPT là một mô hình ngôn ngữ được huấn luyện bằng công nghệ transformer và được phát triển bởi OpenAI. Nó có khả năng học từ dữ liệu văn bản lớn và tự động sinh các câu trả lời liên quan đến các câu hỏi được đặt ra. ChatGPT có thể được sử dụng trong các ứng dụng chatbot, trò chuyện tự động và các hệ thống tư vấn khác. Nó cũng có khả năng tự động hoá các tác vụ như dịch văn bản, tự động điền vào mẫu và các tác vụ khác liên quan đến ngôn ngữ. ChatGPT có khả năng trả lời nhiều loại câu hỏi khác nhau, bao gồm cả câu hỏi có liên quan đến lĩnh vực tri thức, văn hóa, xã hội và các lĩnh vực khác. Nó cũng có thể trả lời các câu hỏi có tính chất hỏi đáp và câu hỏi yêu cầu phân tích sâu hơn. Tuy nhiên, ChatGPT không phải là một người hoặc hệ thống chuyên gia và không thể cung cấp các lời khuyên hoặc đưa ra các quyết định chuyên sâu trong các lĩnh vực cụ thể. Nó chỉ có thể trả lời các câu hỏi dựa trên dữ liệu văn bản mà nó được huấn luyện và không thể đưa ra các lời khuyên hoặc đưa ra các quyết định chuyên sâu."',1, 582, 424, 581),
    (	'LinkedIn-Premium-45',	N'Nâng cấp LinkedIn Premium Business 6 tháng (Đăng kí lần đầu)',	 1,	N'App, Làm việc',	6700000,	91,	'LinkedIn-Premium-45.jpg',	'gia-han-linkedin-premium-6-thang',	N'Làm việc',	N'"LinkedIn là gì? LinkedIn là một mạng xã hội việc làm chuyên nghiệp, nơi bạn có thể kết nối với những người cùng ngành nghề, tìm kiếm việc làm và phát triển nghề nghiệp. LinkedIn có 2 gói đăng ký cơ bản, đó là gói miễn phí và gói trả phí. LinkedIn cùng với Facebook, Instagram, Twitter là các mạng xã hội lớn nhất hiện nay, với rất nhiều người dùng. Hiện nay, LinkedIn thuộc sở hữu của công ty công nghệ Microsoft."	',1	, 238, 644, 561),
    (	'CapCut-Pro-35d-46',	N'CapCut Pro 35 ngày - Tài khoản',	 1,	 N'thiết kế, làm việc',	200000,	60,	'CapCut-Pro-35d-46.png',	'tk-cap-cut-pro-35d',	N'Làm việc',	N'Capcut là ứng dụng cho phép người dùng có thể chỉnh sửa video miễn phí trên điện thoại, có mặt trên hệ điều hành Android, iOS. Capcut có một số tính năng tiện lợi, phục vụ cho người dùng chỉnh sửa video ở mức cơ bản. Ứng dụng này ngày càng được nhiều người ưa thích, sử dụng để biên tập các video trên Tiktok, Instagram,… Capcut được thiết kế đơn giản với bố cục rõ ràng, dễ sử dụng. Chỉ cần một vài thao tác cơ bản là bạn có thể edit video nhanh chóng trên capcut.',1, 283, 5, 466),
    (	'QuillBot-Premium-1t-47',	N'QuillBot Premium 1 tháng 2 thiết bị - Tài khoản',	 1,	N'App, Làm việc, Học tập',	250000,	60,	'QuillBot-Premium-1t-47.png',	'tai-khoan-quillbot-premium-1-thang-2-thiet-bi',	N'Làm việc', N'Tài khoản Quillbot Premium là công cụ sử dụng tính năng AI giúp diễn đạt, hoàn chỉnh câu văn, đoạn văn tiếng Anh. Công cụ này đã giúp cho hàng triệu người tiết kiệm được thời gian trong việc viết bài, khiến cho việc viết trở nên dễ dàng hơn.',1, 64, 266, 590),
    (	'Copilot-Pro-&-Microsoft-365-1t-48',	N'Copilot Pro & Microsoft 365 1 tháng - Tài khoản',	 1,	N'App, New, study, work, học tập, làm việc, ai, ai chat bot, chatgpt',	500000,	80,	'Copilot-Pro-&-Microsoft-365-1t-48.png',	'tai-khoan-copilot-pro-1-thang,',	N'Làm việc',	 N'Microsoft mới đây đã tung ra gói Copilot Pro. Copilot của công ty là AI hoạt động giống như ChatGPT, giúp bạn giải quyết các tác vụ, hoạt động trên Android, iOS và máy tính. Và giờ thì người dùng có thể trả thêm tiền để hưởng các đặc quyền.',1, 327, 250, 469),
    (	'Substance-3D-49',	N'Substance 3D 3 tháng - Nâng cấp chính chủ',	1,	N'App, Làm việc, Adobe, Thiết kế',	2900000,	90,	'Substance-3D-49.png',	'substance-3d-3m',	N'Làm việc',	N'Adobe Substance 3D mang đến một hệ sinh thái các ứng dụng và nội dung giúp bạn thiết kế 3D. Tạo họa tiết cho nội dung và kết xuất cảnh một cách trực quan. Kết nối quy trình làm việc của bạn với các ứng dụng Adobe Creative Cloud.',1, 657, 489, 541),
    (	'Wondershare-Filmora-13-50',	N'Tài khoản Wondershare Filmora 13 (1 năm - 2000 Credit) - MacOS',	1,	N'App, Làm việc',	900000,	78,	'Wondershare-Filmora-13-50.jpg', 'tk-filmora-12-1y-mac'	,N'Làm việc', N'Bạn có thực sự ổn khi phải sử dụng các ứng dụng chỉnh sửa video khó khăn, phức tạp và phải mất hàng giờ mới chỉnh xong một video yêu thích. Thế giới chỉnh sửa video bây giờ đã trở nên dễ dàng hơn nếu bạn biết đến phần mềm Wondershare Filmora 13. Thật quá kì diệu vì người dùng sẽ thoải mái tải nó theo nhiều cách mà không phải mất tiền. Nhưng cái cốt lõi mà khách hàng trở thành một fan cuồng nhiệt của Filmora 13 ở cái hấp dẫn và thú vị mà phần mềm mang lại. Phải nói rằng phần mềm Filmora 13 đã tạo ra một không gian chỉnh sửa video tâm đắc, vừa thoải mái lại linh hoạt hơn bất cứ một phần mềm chỉnh sửa video nào. Tại sao chúng tôi lại nói về Filmora 13 với sự ca ngợi như thế? Điều này phải bắt nguồn từ những tính năng của của phần mềm này.',1, 673, 485, 564),
    (	'iTunes-51',	N'iTunes Gift Card US - 5 USD',	1,	N'Itune',	140000,	0,	'iTunes-51.png',	'itunes-gift-card-5usd',	'Google Play, iTunes',	N'iTune Gift Card là một loại card trả trước của Apple (như thẻ điện thoại) dùng để nạp vào tài khoản iTunes, sau khi nạp vào tài khoản thì tài khoản iTune sẽ có tiền trong đó, bạn có thể dùng thẻ iTunes gift card để thanh toán rất nhiều các dịch vụ mà không cần thẻ Visa / Master của ngân hàng.',1, 582, 681, 96),
    (	'XBox-Microsoft-52',	N'XBox Microsoft Gift Card US - 5$',	1,	N'XBox',	130000,	0,	'XBox-Microsoft-52.png',  'itunes-gift-card-5usd-1'	,'Google Play, iTunes', N'Sau khi nạp thẻ vào account, số tiền này các bạn có thể dùng để mua GAMES, tiền tệ trong game như: gold, gems, kim cương, các bản mở rộng DLC và đăng ký nhiều dịch vụ khác trên hệ thống Xbox. Ngoài ra bạn có thể dùng để thanh toán trên Window Store, Window phone Store....',1, 463, 546, 397),
    (	'iTunes-Gift-53',	N'iTunes Gift Card Turkey - 500 TL',	1,	N'Itune',	480000,	0, 	'iTunes-Gift-53.png',	'itunes-gift-card-500-tl-turkey-tho-nhi-ky',	'Google Play, iTunes',	N'iTune Gift Card là một loại card trả trước của Apple (như thẻ điện thoại) dùng để nạp vào tài khoản iTunes, sau khi nạp vào tài khoản thì tài khoản iTune sẽ có tiền trong đó, bạn có thể dùng thẻ iTunes gift card để thanh toán rất nhiều các dịch vụ mà không cần thẻ Visa / Master của ngân hàng.', 1, 344, 622, 212),
    (	'Google-Play-54',	N'Google Play Gift Card 5 USD (US)',	0,	N'Ggplay, itune, chplay',	145000,	0,	'Google-Play-54.png',	'google-play-gift-card-5-usd',	'Google Play, iTunes', N'"Google Play Gift Card là thẻ trả trước của Google, nó giống như thẻ cào điện thoại, khi các bạn nhập mã số thẻ vào phần ""đổi quà"" trong CHPLAY thì tài khoản của bạn sẽ có tiền trong đó, mỗi lần bạn mua game hay đồ trong game thì CHPLAY sẽ trừ tiền trong tài khoản của bạn. Hướng dẫn đổi Region tại đây."', 1, 204, 675, 246),
    (	'XBox-Microsoft-55',	N'XBox Microsoft Gift Card US - 25$',	1,	N'XBox',	625000,	0,	'XBox-Microsoft-55.png',	'xbox-gift-card-25',	'Google Play, iTunes', N'Sau khi nạp thẻ vào account, số tiền này các bạn có thể dùng để mua GAMES, tiền tệ trong game như: gold, gems, kim cương, các bản mở rộng DLC và đăng ký nhiều dịch vụ khác trên hệ thống Xbox. Ngoài ra bạn có thể dùng để thanh toán trên Window Store, Window phone Store....',1, 81, 18, 27),
    (	'iTunes-Gift-56',	N'iTunes Gift Card US - 10 USD',	1,	N'Itune',	275000,	0,	'iTunes-Gift-56.png',	'itunes-gift-card-10-usd',	'Google Play, iTunes',	N'iTune Gift Card là một loại card trả trước của Apple (như thẻ điện thoại) dùng để nạp vào tài khoản iTunes, sau khi nạp vào tài khoản thì tài khoản iTune sẽ có tiền trong đó, bạn có thể dùng thẻ iTunes gift card để thanh toán rất nhiều các dịch vụ mà không cần thẻ Visa / Master của ngân hàng.', 1, 64, 266, 590),
    (	'iTunes-Gift-57',	N'iTunes Gift Card US - 2 USD',	1,	 N'Itune', 70000,	14,	'iTunes-Gift-57.png',	'itunes-gift-card-2-usd',	'Google Play, iTunes', N'iTune Gift Card là một loại card trả trước của Apple (như thẻ điện thoại) dùng để nạp vào tài khoản iTunes, sau khi nạp vào tài khoản thì tài khoản iTune sẽ có tiền trong đó, bạn có thể dùng thẻ iTunes gift card để thanh toán rất nhiều các dịch vụ mà không cần thẻ Visa / Master của ngân hàng.',1, 72, 46, 4),
    (	'XBox-Microsoft-58',	N'XBox Microsoft Gift Card US - 100$',	 1,	'XBox',	2450000,	0,	'XBox-Microsoft-58.png',	'xbox-gift-card-100',	'Google Play, iTunes',	N'Sau khi nạp thẻ vào account, số tiền này các bạn có thể dùng để mua GAMES, tiền tệ trong game như: gold, gems, kim cương, các bản mở rộng DLC và đăng ký nhiều dịch vụ khác trên hệ thống Xbox. Ngoài ra bạn có thể dùng để thanh toán trên Window Store, Window phone Store....',	1, 382, 502, 595),
    (	'iTunes-Gift-59',	N'iTunes Gift Card Turkey - 250 TL',	1,	 'Itune',	245000,	0,	'iTunes-Gift-59.png',	'itunes-gift-card-250-tl-turkey-tho-nhi-ky',	'Google Play, iTunes',	N'iTune Gift Card là một loại card trả trước của Apple (như thẻ điện thoại) dùng để nạp vào tài khoản iTunes, sau khi nạp vào tài khoản thì tài khoản iTune sẽ có tiền trong đó, bạn có thể dùng thẻ iTunes gift card để thanh toán rất nhiều các dịch vụ mà không cần thẻ Visa / Master của ngân hàng.',1, 238, 644, 561),
    (	'iTunes-Gift-60',	N'iTunes Gift Card Turkey - 50 TL'	, 1	, 'Itune',	50000,	0,	'iTunes-Gift-60.png',	'itunes-gift-card-50-tl-turkey-tho-nhi-ky',	'Google Play, iTunes',	N'iTune Gift Card là một loại card trả trước của Apple (như thẻ điện thoại) dùng để nạp vào tài khoản iTunes, sau khi nạp vào tài khoản thì tài khoản iTune sẽ có tiền trong đó, bạn có thể dùng thẻ iTunes gift card để thanh toán rất nhiều các dịch vụ mà không cần thẻ Visa / Master của ngân hàng.',1, 382, 502, 595),
    (	'SteamWallet-61',	N'Steam Wallet Code 40 HKD',	1, '',136000,	0,	'SteamWallet-61.png',	'steam-wallet-code-40-hkd',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.	',1, 283, 5, 466),
    (	'SteamWallet-62',	N'Steam Wallet Code 80 HKD',	1,	'',	272000,	0,	'SteamWallet-62.png',	'steam-wallet-code-80hkd',	'Steam Wallet', N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 72, 46, 4),
    (	'SteamWallet-63',	N'Gói nạp Steam Wallet 20$',	1,	'steam, wallet, goinapwallet',	490000,	0,	'SteamWallet-63.png',	'goi-nap-steam-wallet-20',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.	', 1, 574, 681, 344),
    (	'SteamWallet-64',	N'Steam Wallet Code 100 TWD',	1,	'',	93000,	0,	'SteamWallet-64.png',	'code-steam-100twd',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 126, 697, 304),
    (	'SteamWallet-65',	N'Gói nạp Steam Wallet 50$',	1,	'steam, wallet, goinapwallet',	1300000,	0,	'SteamWallet-65.png',	'goi-nap-steam-wallet-50',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 460, 554, 141),
    (	'SteamWallet-66',	N'Steam Wallet Code 50 HKD',	1,	'',	172000,	0,	'SteamWallet-66.png',	'steam-wallet-code-50hkd',	'Steam Wallet', N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.	',1, 81, 18, 27),
    (	'SteamWallet-67',	N'Gói nạp Steam Wallet 100$',	1,	'steam, wallet, goinapwallet',	2400000,	0,	'SteamWallet-67.png',	'goi-nap-steam-wallet-100',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 535, 328, 661),
    (	'SteamWallet-68',	N'Steam Wallet Code 100 HKD',	1,	'',	341000,	0,	'SteamWallet-68.png',	'steam-wallet-code-100-hkd',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 686, 407, 327),
    (	'SteamWallet-69',	N'Steam Wallet Code 150 TWD',	1,	'',	128000,	0,	'SteamWallet-69.png',	'steam-wallet-code-150twd',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 316, 545, 678),
    (	'SteamWallet-70',	N'Steam Wallet Code 120 HKD',	1,	'',	409000,	0,	'SteamWallet-70.png',	'steam-wallet-code-120hkd',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 82, 626, 33),
    (	'SteamWallet-71',	'Steam Wallet Code 150 TWD-1',	1,	'',	128000,	0,	'SteamWallet-71.png',	'steam-wallet-code-150twd-1',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 204, 675, 246),
    (	'SteamWallet-72',	'Steam Wallet Code 200 HKD',	1,	'',	672000,	0,	'SteamWallet-72.png',	'steam-wallet-code-200hkd',	'Steam Wallet', N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 686, 407, 327),
    (	'SteamWallet-73',	'Steam Wallet Code 400 HKD',	1,	'',	1334000,	0,	'SteamWallet-73.png',	'steam-wallet-code-400hkd',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 119, 70, 369),
    (	'SteamWallet-74',	'Steam Wallet Code 300 HKD',	1,	'',	999000,	0,	'SteamWallet-74.png',	'steam-wallet-code-300hkd',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 263, 414, 47),
    (	'SteamWallet-75',	'Steam Wallet Code 240 HKD',	1,	'',	807000,	0,	'SteamWallet-75.png',	'steam-wallet-code-240hkd',	'Steam Wallet', N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 65, 25, 62),
    (	'SteamWallet-76',	'Steam Wallet Code 600 HKD',	1,	'',	1996000,	0,	'SteamWallet-76.png',	'steam-wallet-code-600hkd',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 420, 350, 325),
    (	'SteamWallet-77',	'Steam Wallet Code 100 THB',	1,	'',	86000,	0,	'SteamWallet-77.png',	'code-steam-100thb',	'Steam Wallet',	N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 2, 506, 163),
    (	'SteamWallet-78',	'steam-wallet-code-200twd',	0,	'',	170000,	0,	'SteamWallet-78.png',	'Steam-Wallet-Code-200-TWD',	'Steam Wallet', N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 252, 511, 330),
    (	'SteamWallet-79',	'Steam Wallet Code 150 HKD',	0,	'',	504000,	0,	'SteamWallet-79.png',	'Steam-Wallet-Code-150-HKD',	'Steam Wallet', N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 252, 511, 330),
    (	'SteamWallet-80',	'Steam Wallet Code 300 TWD',	0,	'',	256000,	0,	'SteamWallet-80.png',	'Steam-Wallet-Code-300-TWD',	'Steam Wallet', N'Steam Wallet Code không còn lạ lẫm gì nữa với cộng đồng game thủ nữa khi nó ngày một được ưa chuộng và thịnh hành hơn so với nạp card Steam Wallet bởi khả năng nạp nhanh, cơ hội được chiết khấu lớn và đặc biệt là không cần phải chờ đợi ship hàng. Sau khi mua code xong bạn sẽ nhận được ngay lập tức mã code để nạp vào tài khoản Steam của mình.',1, 82, 626, 33),
    (	'CanvaPro-81',	N'Canva Pro 1 tháng - Tài khoản',	1,	N'App, Làm việc, Thiết kế',	150000,	83,	'CanvaPro-81.png',	'canva-pro-1-thang-tai-khoan',	'Edit',	N'Tài khoản canva giá rẻ chứa đầy đủ tài nguyên thiết kế miễn phí mà bạn có thể sử dụng ngay từ bên trong ứng dụng hoặc trang web và bắt đầu tạo đồ họa cho trang web, banner, mẫu bìa quảng cáo và phương tiện truyền thông xã hội của bạn. Canva là một công cụ tuyệt vời cho mọi người phải tạo đồ họa hoặc chỉnh sửa ảnh trong thời gian ngắn mà không cần bất kỳ kỹ năng thiết kế nào.',1, 344, 622, 212),
    (	'CanvaPro-82',	N'Canva Pro 1 năm -- Gia hạn chính chủ',	1,	N'App, Làm việc, Thiết kế',	1500000,	80,	'CanvaPro-82.png',	'canva-pro-1-nam-gia-han-chinh-chu',	'Edit',	N'Tài khoản canva giá rẻ chứa đầy đủ tài nguyên thiết kế miễn phí mà bạn có thể sử dụng ngay từ bên trong ứng dụng hoặc trang web và bắt đầu tạo đồ họa cho trang web, banner, mẫu bìa quảng cáo và phương tiện truyền thông xã hội của bạn. Canva là một công cụ tuyệt vời cho mọi người phải tạo đồ họa hoặc chỉnh sửa ảnh trong thời gian ngắn mà không cần bất kỳ kỹ năng thiết kế nào.',1, 582, 681, 96),
    (	'ExpressVPN-83',	N'ExpressVPN 1 tháng (5 thiết bị) - Tài khoản',	1,	N'App, congviec, vpn, fake ip',	500000,	0,	'ExpressVPN-83.png',	'expressvpn-1-thang-5-thiet-bi',	'Edit',	 N'ExpressVPN là nhà cung cấp VPN tốt nhất trong phân lớp. VPN này cung cấp mức độ bảo mật cao nhất và một số lượng lớn các máy chủ, trải rộng trên 94 quốc gia. Mặc dù có chi phí cao hơn đáng kể so với các đối thủ cạnh tranh, ExpressVPN vẫn là sự lựa chọn số 1 cho các doanh nghiệp cần một giải pháp VPN chất lượng hàng đầu.',1, 686, 407, 327),
    (	'ExpressVPN-84',	N'ExpressVPN 1 tháng (1 thiết bị) - Tài khoản',	1,	N'App, congviec, vpn, fake ip',	300000,	0,	'ExpressVPN-84.png',	'expressvpn-1-thang-1-thiet-bi',	'Edit',	N'ExpressVPN là nhà cung cấp VPN tốt nhất trong phân lớp. VPN này cung cấp mức độ bảo mật cao nhất và một số lượng lớn các máy chủ, trải rộng trên 94 quốc gia. Mặc dù có chi phí cao hơn đáng kể so với các đối thủ cạnh tranh, ExpressVPN vẫn là sự lựa chọn số 1 cho các doanh nghiệp cần một giải pháp VPN chất lượng hàng đầu.',1, 81, 18, 27),
    (	'CanvaPro-85',	N'Canva Pro 1 tháng - Gia hạn chính chủ',	1,	N'App, Làm việc, Thiết kế',	150000,	80,	'CanvaPro-85.png',	'canva-pro-1-thang-gia-han-chinh-chu',	'Edit', N'Tài khoản canva giá rẻ chứa đầy đủ tài nguyên thiết kế miễn phí mà bạn có thể sử dụng ngay từ bên trong ứng dụng hoặc trang web và bắt đầu tạo đồ họa cho trang web, banner, mẫu bìa quảng cáo và phương tiện truyền thông xã hội của bạn. Canva là một công cụ tuyệt vời cho mọi người phải tạo đồ họa hoặc chỉnh sửa ảnh trong thời gian ngắn mà không cần bất kỳ kỹ năng thiết kế nào.',1, 344, 622, 212),
    (	'FullApp80GBCloud-86',	N'Phần mềm thiết kế Full App 80GB Cloud 1 năm - Tài khoản',	1,	N'pts , photoshop',	15000000,	9,	'FullApp80GBCloud-86.jpg',	'phan-mem-thiet-ke-full-app-80gb-could-1-nam-tai-khoan',	'Edit','', 1, 263, 414, 47),
    (	'FullAppNoCloud-87',	N'Phần mềm thiết kế Full App No Cloud 1 năm - Tài khoản',	1,	N'pts , photoshop',	15000000,	0,	'FullAppNoCloud-87.jpg',	'phan-mem-thiet-ke-full-app-no-could-1-nam-tai-khoan',	'Edit','',1, 82, 626, 33),
    (	'FullApp100GBCloud-88',	N'Phần mềm thiết kế Full App 100GB Cloud 1 tháng - Code kích hoạt',	1,	'pts , photoshop',	1500000,	0,	'FullApp100GBCloud-88.jpg',	'phan-mem-thiet-ke-full-app-100gb-could-1-thang-code-kich-hoat',	'Edit','',	1, 574, 681, 344),
    (	'FullApp1000GBCloud-89',	N'Phần mềm thiết kế Full App 1000GB Cloud 1 tháng - Nâng cấp chính chủ',	1,	'pts , photoshop',	950000,	6,	'FullApp1000GBCloud-89.jpg',	'phan-mem-thiet-ke-full-app-1000gb-could-1-thang-nang-cap-chinh-chu',	'Edit','',1, 126, 697, 304),
    (	'CreativeFabrica-90',	N'Tài khoản Creative Fabrica (1 tháng)',	1,	N'thiết kế, làm việc',	1500000,	7,	'CreativeFabrica-90.jpg',	'tai-khoan-creative-fabrice-1-thang',	'Edit',	N'Creative Fabrica là một trang web cung cấp hình ảnh đồ hoạ cho các nhà thiết kế đồ họa và phông chữ. Bạn sẽ tìm thấy hơn hai triệu phông chữ chất lượng cao, file định dạng (SVG và DXF), các mẫu thiết kế và font chữ cho Print On Demand (POD) và rất nhiều các hình ảnh đồ thủ công mỹ nghệ.',1, 327, 250, 469),
    (	'CreativeFabrica-91',	N'Creative Fabrica 1 tháng 10 files - Tài khoản',	1,	N'thiết kế, làm việc',	240000,	8,	'CreativeFabrica-91.jpg',	'creative-fabrice-1-thang-10-files-tai-khoan',	'Edit',	N'Creative Fabrica là một trang web cung cấp hình ảnh đồ hoạ cho các nhà thiết kế đồ họa và phông chữ. Bạn sẽ tìm thấy hơn hai triệu phông chữ chất lượng cao, file định dạng (SVG và DXF), các mẫu thiết kế và font chữ cho Print On Demand (POD) và rất nhiều các hình ảnh đồ thủ công mỹ nghệ.	',1, 686, 407, 327),
    (	'CapCutPro-92',	N'CapCut Pro 70 ngày - Tài khoản',	1,	N'thiết kế, làm việc',	479000,	9,	'CapCutPro-92.png',	'capcut-pro-70-ngay-tai-khoan',	'Edit',	N'Capcut là ứng dụng cho phép người dùng có thể chỉnh sửa video miễn phí trên điện thoại, có mặt trên hệ điều hành Android, iOS. Capcut có một số tính năng tiện lợi, phục vụ cho người dùng chỉnh sửa video ở mức cơ bản. Ứng dụng này ngày càng được nhiều người ưa thích, sử dụng để biên tập các video trên Tiktok, Instagram,…',1, 252, 511, 33),
    (	'CapCutPro-93',	N'CapCut Pro 35 ngày - Tài khoản',	1,	N'thiết kế, làm việc',	200000,	0,	'CapCutPro-93.png',	'capcut-pro-35-ngay-tai-khoan',	'Edit',	N'Capcut là ứng dụng cho phép người dùng có thể chỉnh sửa video miễn phí trên điện thoại, có mặt trên hệ điều hành Android, iOS. Capcut có một số tính năng tiện lợi, phục vụ cho người dùng chỉnh sửa video ở mức cơ bản. Ứng dụng này ngày càng được nhiều người ưa thích, sử dụng để biên tập các video trên Tiktok, Instagram,…',1, 65, 25, 62),
    (	'HmaVpnCdKey-94',	N'HMA VPN CD Key (1 Năm - 5 Thiết bị)',	1,	'App, congviec',	1400000,	8,	'HmaVpnCdKey-94.png',	'hma-vpn-cd-key-1-nam-5-thiet-bi',	'Edit',	N'HMA VPN là một loại VPN rất nhanh và dễ sử dụng Chọn trong số hơn 290 địa điểm tại hơn 190 quốc gia: Chưa có đối thủ. Tận hưởng các máy chủ có tốc độ 20 Gbps, khiến chúng tôi trở thành một trong những VPN nhanh nhất trên thị trường',1, 686, 407, 327),
    (	'DataboxDataEditor-95',	N'Databox - Data Editor & Save Solution Unity kích hoạt vĩnh viễn',	1,	'App, thiet ket, new',	1500000,	8,	'DataboxDataEditor-95.png',	'databox-data-editor-save-solution-unity-kich-hoat-vinhc-vien',	'Edit', N'Databox - Data Editor & Save Solution là một công cụ quản lý và lưu trữ dữ liệu mạnh mẽ dành cho Unity.',1, 535, 328, 661),
    (	'HdrPhotomatixPro-96',	N'HDR Photomatix Pro 6.3 - Key kích hoạt vĩnh viễn',	1,	'App, thiet ket, new',	2300000,	4,	'HdrPhotomatixPro-96.png',	'hdr-photomatix-pro-6.4-key-kich-hoat-vinh-vien',	'Edit',	N'Photomatix Pro là một phần mềm hình ảnh động High Dynamic Range (HDR) tiên tiến cho phép người dùng tạo ra các bức ảnh HDR hoàn hảo. Với Photomatix bạn có thể tạo các hình ảnh HDR cho thấy cả chi tiết nổi bật và bóng trong tất cả các khu vực . Một số công cụ và cài đặt được cung cấp để giúp điều chỉnh ánh sáng dễ dàng hơn, xóa bóng / bóng ma, giảm tiếng ồn, quang sai màu và hơn thế nữa. Điều này chắc chắn sẽ rất hữu ích cho các nhiếp ảnh gia để tạo ra những hình ảnh chất lượng tốt từ các kết quả tự nhiên đến hình ảnh có điều kiện ánh sáng yếu.',1, 126, 697, 304);
go

go
INSERT INTO [Category] (ten_the_loai)
VALUES
    (N'App'),
    (N'Giải trí'),
    (N'Xem phim'),
    (N'Spotify'),
    (N'Nghe nhạc'),
    (N'Youtube'),
    (N'New'),
    (N'Làm việc'),
    (N'Diệt virus'),
    (N'kaspersky'),
    (N'steam'),
    (N'Action'),
    (N'RPG'),
    ('acc'),
    (N'Học tập'),
    ('openai'),
    ('chatgpt'),
    ('microsoft'),
    ('Adobe'),
    (N'Thiết kế'),
    ('XBox'),
    ('wallet'),
    ('Itune'),
    ('vpn'),
    ('photoshop'),
    ('thiet ket'),
    ('pts'),
    ('chplay');
go

go
INSERT INTO [Discount] (ten_giam_gia, percent_giam_gia, ngay_bat_dau, ngay_ket_thuc, mota)
VALUES
    ('4/4','50','2024-05-29','2024-05-31','')
go